name: mypy
on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install types-docutils
        pip install -r sphinxcontrib/requirements.txt
        python3 -m mypy sphinxcontrib --install-types --non-interactive
    - name: run mypy
      run: |
        export PYTHONPATH='.'
        python -m mypy sphinxcontrib
